apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tkgs-cluster-2
  namespace: sk8s1
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-xsmall
      storageClass: kubernetes-gold-storage-policy
      volumes:
        - name: etcd
          mountPath: /var/lib/etcd
          capacity:
            storage: 4Gi
      tkr:
        reference:
          name: v1.21.6---vmware.1-tkg.1.b3d708a
    nodePools:
    - name: worker-nodepool-a1
      replicas: 2
      vmClass: best-effort-xsmall
      storageClass: kubernetes-gold-storage-policy
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 16Gi
      tkr:
        reference:
          name: v1.21.6---vmware.1-tkg.1.b3d708a
    # - name: worker-nodepool-a2
    #   replicas: 2
    #   vmClass: best-effort-xsmall
    #   storageClass: kubernetes-gold-storage-policy
    #   tkr:
    #     reference:
    #       name: v1.21.6---vmware.1-tkg.1.b3d708a
  settings:
    storage:
      defaultClass: kubernetes-gold-storage-policy